### ISSUE TITLE
$is_code check could be improved

### ISSUE THREAD

**Issue by tobyink** [reneeb/Tie-CheckVariables#1]
```
my $is_code = grep{ $_ eq ref $check }qw(CODE Type::Tiny);
```

Using `ref` to check blessed objects isn't a great idea because it ignores subclasses.

For example:

```
perl -MTypes::Standard=-all -E'say ref Int'
```
Result: `Type::Tiny`. Everything good so far.

```
perl -MTypes::Standard=-all -E'say ref Enum[1..5]'
```
Result: `Type::Tiny::Enum`. Will fail your `$is_code` check.

A better check would be:

```
use Scalar::Util;
my $is_code = (ref($check) eq 'CODE') || (blessed($check) && $check->isa('Type::Tiny'));
```

An alternative would be in `TIESCALAR` to convert the Type::Tiny object to a plain coderef. Something like this:

```
sub TIESCALAR{
    my ($class, $type) = @_;
   
    my $self = {};
    bless $self, $class;
 
    $self->_type(blessed($type) ? $type->compiled_check : $type);
         
    return $self;
}
```

The latter method should give you a small speed boost too, because the coderefs that Type::Tiny generates are pretty efficient, and you'll avoid some of the CPU overhead of using method calls, overloaded objects, etc.

**Comment by reneeb** [comment]
Thanks, fixed in 0.05
