### ISSUE TITLE
SYNOPSIS code is misleading

### ISSUE THREAD

**Issue by manwar** [reneeb/Tie-CheckVariables#3]
Hi @reneeb 

I noticed the SYNOPSIS code below doesn't throw error as per the comment:

       use Tie::CheckVariables
 
        tie my $scalar,'Tie::CheckVariables','integer';
        $scalar = 88; # is ok
        $scalar = 'test'; # is not ok, throws error
 
        untie $scalar;

Did I miss something?

Best Regards,
Mohammad S Anwar

**Comment by reneeb** [comment]
As of version 0.05 it should throw an error... I've added a new test case for the synopsis code.
